import type { Dataset } from "../schema.js";
import { TABLES, type Column } from "./tables.js";

/** Pretty-printed JSON with a trailing newline. Byte-identical for identical input. */
export function toJSON(dataset: Dataset): string {
  return `${JSON.stringify(dataset, null, 2)}\n`;
}

/** The event timeline as newline-delimited JSON, one BusinessEvent per line. */
export function toNDJSONEvents(dataset: Dataset): string {
  return dataset.events.map((e) => JSON.stringify(e)).join("\n") + (dataset.events.length ? "\n" : "");
}

export function csvCell(value: unknown): string {
  if (value === null || value === undefined) return "";
  const s = typeof value === "string" ? value : typeof value === "object" ? JSON.stringify(value) : String(value);
  return /[",\r\n]/.test(s) || s.startsWith(" ") || s.endsWith(" ") ? `"${s.replace(/"/g, '""')}"` : s;
}

export function toCSV(headers: readonly string[], rows: ReadonlyArray<readonly unknown[]>): string {
  return [headers.map(csvCell).join(","), ...rows.map((r) => r.map(csvCell).join(","))].join("\r\n") + "\r\n";
}

function cellValue(c: Column, row: unknown): unknown {
  const v = c.get(row);
  if (c.type === "json") return v === null ? null : JSON.stringify(v);
  return v;
}

/**
 * One RFC 4180 CSV per collection (plus company, policies and line-item
 * tables), keyed by file name, e.g. `{ "customers.csv": "id,kind,..." }`.
 * Nested arrays/objects are JSON-encoded in their cell.
 */
export function toCSVFiles(dataset: Dataset): Record<string, string> {
  const out: Record<string, string> = {};
  for (const t of TABLES) {
    out[`${t.name}.csv`] = toCSV(
      t.columns.map((c) => c.name),
      t.rows(dataset).map((r) => t.columns.map((c) => cellValue(c, r))),
    );
  }
  return out;
}

function sqlLiteral(value: unknown, c: Column, dialect: "sqlite" | "postgres"): string {
  const v = cellValue(c, value);
  if (v === null || v === undefined) return "NULL";
  if (c.type === "bool") return dialect === "postgres" ? (v ? "TRUE" : "FALSE") : v ? "1" : "0";
  if (c.type === "int") return String(Math.trunc(Number(v)));
  const s = `'${String(v).replace(/'/g, "''")}'`;
  return c.type === "json" && dialect === "postgres" ? `${s}::jsonb` : s;
}

function sqlType(c: Column, dialect: "sqlite" | "postgres"): string {
  switch (c.type) {
    case "int":
      return dialect === "postgres" ? "BIGINT" : "INTEGER";
    case "bool":
      return dialect === "postgres" ? "BOOLEAN" : "INTEGER";
    case "json":
      return dialect === "postgres" ? "JSONB" : "TEXT";
    default:
      return "TEXT";
  }
}

/** A self-contained SQL script: DROP/CREATE TABLE per collection, then INSERTs, in one transaction. */
export function toSQL(dataset: Dataset, dialect: "sqlite" | "postgres" = "sqlite"): string {
  if (dialect !== "sqlite" && dialect !== "postgres") throw new RangeError(`Unknown SQL dialect "${String(dialect)}"`);
  const q = (id: string) => `"${id}"`;
  const lines: string[] = [
    `-- ${dataset.company.name}: synthetic dataset generated by ${dataset.meta.generator} ${dataset.meta.generatorVersion}`,
    `-- industry=${dataset.meta.industry} seed=${dataset.meta.seed} ${dataset.meta.startDate}..${dataset.meta.asOf}. All data is fictional.`,
    "BEGIN;",
  ];
  for (const t of [...TABLES].reverse()) lines.push(`DROP TABLE IF EXISTS ${q(t.name)};`);
  for (const t of TABLES) {
    const cols = t.columns.map((c) => `  ${q(c.name)} ${sqlType(c, dialect)}${t.primaryKey.length === 1 && t.primaryKey[0] === c.name ? " PRIMARY KEY" : ""}`);
    if (t.primaryKey.length > 1) cols.push(`  PRIMARY KEY (${t.primaryKey.map(q).join(", ")})`);
    lines.push(`CREATE TABLE ${q(t.name)} (\n${cols.join(",\n")}\n);`);
  }
  for (const t of TABLES) {
    const names = t.columns.map((c) => q(c.name)).join(", ");
    for (const row of t.rows(dataset)) {
      lines.push(`INSERT INTO ${q(t.name)} (${names}) VALUES (${t.columns.map((c) => sqlLiteral(row, c, dialect)).join(", ")});`);
    }
  }
  lines.push("COMMIT;");
  return `${lines.join("\n")}\n`;
}

const HUBSPOT_STAGE: Record<string, string> = {
  new: "Appointment Scheduled",
  qualified: "Qualified To Buy",
  "quote-sent": "Contract Sent",
  negotiation: "Decision Maker Bought-In",
  won: "Closed Won",
  lost: "Closed Lost",
};

function domainOf(email: string | null): string {
  return email?.includes("@") ? (email.split("@")[1] ?? "") : "";
}

/**
 * CSVs whose headers follow HubSpot's default property labels for contacts,
 * companies and deals, plus an "External ID" column with the dataset id. Map
 * columns in HubSpot's import wizard; this is not an official template.
 */
export function toHubSpotImportCSVs(dataset: Dataset): Record<string, string> {
  const employees = new Map(dataset.employees.map((e) => [e.id, e]));
  const customers = new Map(dataset.customers.map((c) => [c.id, c]));
  const contacts = new Map(dataset.contacts.map((c) => [c.id, c]));
  const business = dataset.company.industry === "marketing-agency";
  const stageByCustomer = new Map<string, string>();
  for (const d of dataset.deals) {
    const prev = stageByCustomer.get(d.customerId);
    if (d.stage === "won" || (!prev && d.stage !== "lost")) stageByCustomer.set(d.customerId, d.stage === "won" ? "customer" : "opportunity");
  }
  const contactRows = dataset.contacts.map((c) => {
    const cus = c.customerId ? customers.get(c.customerId) : undefined;
    const lifecycle = cus ? (stageByCustomer.get(cus.id) ?? "customer") : "lead";
    return [
      c.firstName, c.lastName, c.email, c.phone, c.title, lifecycle,
      business && cus ? cus.name : "",
      cus?.address.line1 ?? "", cus?.address.city ?? "", cus?.address.region ?? "", cus?.address.postalCode ?? "",
      cus?.ownerId ? (employees.get(cus.ownerId)?.email ?? "") : "",
      c.createdAt.slice(0, 10), c.id,
    ];
  });
  const companyRows = business
    ? dataset.customers.map((cus) => {
        const primary = dataset.contacts.find((c) => c.customerId === cus.id);
        return [
          cus.name, domainOf(primary?.email ?? null), primary?.phone ?? "", cus.address.line1, cus.address.city, cus.address.region,
          cus.address.postalCode, "United States", stageByCustomer.get(cus.id) ?? "customer",
          cus.ownerId ? (employees.get(cus.ownerId)?.email ?? "") : "", cus.id,
        ];
      })
    : [];
  const dealRows = dataset.deals.map((d) => {
    const contact = contacts.get(d.contactId);
    return [
      d.title, "Sales Pipeline", HUBSPOT_STAGE[d.stage] ?? d.stage, (d.amountCents / 100).toFixed(2),
      d.closedAt ? d.closedAt.slice(0, 10) : (d.nextAction?.dueOn ?? ""), d.createdAt.slice(0, 10),
      d.ownerId ? (employees.get(d.ownerId)?.email ?? "") : "", contact?.email ?? "",
      business ? (customers.get(d.customerId)?.name ?? "") : "", d.lostReason ?? "", d.id,
    ];
  });
  return {
    "contacts.csv": toCSV(
      ["First Name", "Last Name", "Email", "Phone Number", "Job Title", "Lifecycle Stage", "Company Name", "Street Address", "City", "State/Region", "Postal Code", "Contact Owner", "Create Date", "External ID"],
      contactRows,
    ),
    "companies.csv": toCSV(
      ["Company Name", "Company Domain Name", "Phone Number", "Street Address", "City", "State/Region", "Postal Code", "Country/Region", "Lifecycle Stage", "Company Owner", "External ID"],
      companyRows,
    ),
    "deals.csv": toCSV(
      ["Deal Name", "Pipeline", "Deal Stage", "Amount", "Close Date", "Create Date", "Deal Owner", "Associated Contact Email", "Associated Company Name", "Closed Lost Reason", "External ID"],
      dealRows,
    ),
  };
}

/**
 * Customer and invoice CSVs with column names modeled on common QuickBooks
 * Online import spreadsheets (one row per invoice line). Not an official
 * template; review the column mapping when importing.
 */
export function toQuickBooksImportCSVs(dataset: Dataset): Record<string, string> {
  const customers = new Map(dataset.customers.map((c) => [c.id, c]));
  const terms = dataset.company.paymentTermsDays === 0 ? "Due on receipt" : `Net ${dataset.company.paymentTermsDays}`;
  const customerRows = dataset.customers.map((cus) => {
    const primary = dataset.contacts.find((c) => c.customerId === cus.id);
    return [
      cus.name, cus.kind === "business" ? cus.name : "", primary ? `${primary.firstName} ${primary.lastName}` : "",
      primary?.email ?? "", primary?.phone ?? "", cus.address.line1, cus.address.city, cus.address.region,
      cus.address.postalCode, "US", terms, cus.id,
    ];
  });
  const invoiceRows = dataset.invoices.flatMap((inv) =>
    inv.lineItems.map((l) => [
      inv.number, customers.get(inv.customerId)?.name ?? inv.customerId, inv.issuedOn, inv.dueOn, terms,
      `Job ${inv.jobId ?? "n/a"}`, l.sku, l.description, l.quantity, (l.unitPriceCents / 100).toFixed(2),
      ((l.quantity * l.unitPriceCents) / 100).toFixed(2), inv.issuedOn,
    ]),
  );
  return {
    "customers.csv": toCSV(
      ["Name", "Company", "Contact Name", "Email", "Phone", "Billing Address Line 1", "Billing Address City", "Billing Address State", "Billing Address Postal Code", "Billing Address Country", "Terms", "External ID"],
      customerRows,
    ),
    "invoices.csv": toCSV(
      ["InvoiceNo", "Customer", "InvoiceDate", "DueDate", "Terms", "Memo", "Item(Product/Service)", "ItemDescription", "ItemQuantity", "ItemRate", "ItemAmount", "Service Date"],
      invoiceRows,
    ),
  };
}
