import type { IndustryProfile } from "./types.js";

export const dentalClinic: IndustryProfile = {
  id: "dental-clinic",
  name: "Dental clinic",
  summary:
    "General dental practice: patients, appointments, 6-month hygiene recalls, treatment plans and insurance-style billing notes (no real PHI).",
  companyNames: [
    "Juniper Smiles Dentistry",
    "Maple Grove Family Dental",
    "Brightwater Dental Studio",
    "Kestrel Point Dental Care",
    "Clearbrook Family Dentistry",
    "Stonebrook Dental Group",
  ],
  companyDescription: "General and family dentistry: cleanings, restorative treatment and cosmetic care",
  customerKind: "household",
  nouns: { quote: "treatment plan", job: "appointment", customer: "patient" },
  quotePrefix: "TP-",
  quoteValidDays: 60,
  paymentTermsDays: 14,
  openDays: [1, 2, 3, 4, 5],
  roster: [
    { role: "owner", small: 1, medium: 1, large: 1 },
    { role: "dentist", small: 0, medium: 1, large: 3 },
    { role: "hygienist", small: 1, medium: 2, large: 5 },
    { role: "front-desk", small: 1, medium: 2, large: 3 },
    { role: "office-manager", small: 0, medium: 1, large: 1 },
    { role: "bookkeeper", small: 0, medium: 0, large: 1 },
  ],
  salesRoles: ["front-desk", "office-manager"],
  schedulerRoles: ["front-desk"],
  policies: [
    { title: "Cancellations", rule: "Patients should give 24 hours' notice to cancel; after two no-shows a deposit is required to book." },
    { title: "Insurance estimates", rule: "Insurance estimates are not a guarantee of payment; the patient is responsible for any remaining balance." },
    { title: "Hygiene recall", rule: "Adult patients are recalled for a cleaning and exam every 6 months." },
    { title: "Privacy in messages", rule: "Never put diagnoses or treatment details in texts or email subject lines; refer to appointments by date and time only." },
    { title: "Patient balances", rule: "Patient portions are due within 14 days of the visit." },
    { title: "Treatment plans", rule: "Treatment plans are valid for 60 days; fees are re-estimated after that." },
  ],
  catalog: [
    { sku: "EXAM-NP", description: "Comprehensive exam, new patient", unitPriceCents: 14500 },
    { sku: "EXAM-PER", description: "Periodic exam", unitPriceCents: 6500 },
    { sku: "EXAM-LTD", description: "Limited exam, problem-focused", unitPriceCents: 9500 },
    { sku: "XRAY-FMX", description: "Full-mouth X-ray series", unitPriceCents: 16500 },
    { sku: "XRAY-BWX", description: "Bitewing X-rays, four films", unitPriceCents: 7200 },
    { sku: "XRAY-PA", description: "Periapical X-ray, single film", unitPriceCents: 3500 },
    { sku: "PROPHY", description: "Adult cleaning (prophylaxis)", unitPriceCents: 12500 },
    { sku: "FLUOR", description: "Fluoride varnish", unitPriceCents: 4500 },
    { sku: "FILL-COMP", description: "Composite filling, one surface", unitPriceCents: 21000 },
    { sku: "BUILDUP", description: "Core buildup", unitPriceCents: 29500 },
    { sku: "CROWN-ZR", description: "Zirconia crown", unitPriceCents: 135000 },
    { sku: "RCT-MOLAR", description: "Root canal therapy, molar", unitPriceCents: 125000 },
    { sku: "SRP-QUAD", description: "Scaling and root planing, per quadrant", unitPriceCents: 26000 },
    { sku: "EXT-SIMPLE", description: "Simple extraction", unitPriceCents: 22500 },
    { sku: "WHITEN", description: "In-office whitening", unitPriceCents: 49500 },
    { sku: "NIGHTGUARD", description: "Custom night guard", unitPriceCents: 42500 },
  ],
  offerings: [
    {
      key: "new-patient",
      title: "New patient exam and cleaning",
      weight: 4,
      quote: false,
      newOnly: true,
      lines: [
        { sku: "EXAM-NP", qty: [1, 1] },
        { sku: "XRAY-FMX", qty: [1, 1] },
        { sku: "PROPHY", qty: [1, 1] },
        { sku: "FLUOR", qty: [1, 1], p: 0.3 },
      ],
      durationMin: [60, 90],
      crew: ["hygienist", "dentist"],
      billing: "on-completion",
      recurring: { everyMonths: 6, offering: "hygiene-recall" },
      leadTimeDays: [3, 14],
      requests: [
        "We just moved to the area and need a new dentist for the whole family. Do you accept PPO insurance?",
        "I haven't been to a dentist in a few years and I'd like to get a cleaning and checkup. Are you taking new patients?",
        "Looking for a new dentist close to work. Do you have any early morning appointments?",
        "My coworker recommended you. I'd like to book a new patient visit.",
      ],
    },
    {
      key: "hygiene-recall",
      title: "Hygiene visit and periodic exam",
      weight: 0,
      quote: false,
      lines: [
        { sku: "EXAM-PER", qty: [1, 1] },
        { sku: "PROPHY", qty: [1, 1] },
        { sku: "XRAY-BWX", qty: [1, 1], p: 0.5 },
        { sku: "FLUOR", qty: [1, 1], p: 0.2 },
      ],
      durationMin: [60, 60],
      crew: ["hygienist", "dentist"],
      billing: "on-completion",
      leadTimeDays: [2, 14],
      requests: ["Due for my six-month cleaning."],
    },
    {
      key: "emergency",
      title: "Emergency visit",
      weight: 1.8,
      quote: false,
      lines: [
        { sku: "EXAM-LTD", qty: [1, 1] },
        { sku: "XRAY-PA", qty: [1, 2] },
        { sku: "FILL-COMP", qty: [1, 1], p: 0.4 },
        { sku: "EXT-SIMPLE", qty: [1, 1], p: 0.15 },
      ],
      durationMin: [30, 60],
      crew: ["dentist"],
      billing: "on-completion",
      leadTimeDays: [1, 1],
      requests: [
        "I chipped a tooth on something hard last night and it's sensitive. Can I be seen today?",
        "Bad toothache on the lower left since the weekend, worse when I chew. Any openings?",
        "A filling fell out this morning. How soon can you fit me in?",
      ],
      repeatRequests: [
        "Hi, I'm already a patient. I chipped a tooth last night and it's sensitive. Can I be seen today?",
        "It's me again. A filling you placed fell out this morning. How soon can you fit me in?",
        "I'm a patient of yours and I've had a bad toothache since the weekend. Any openings?",
      ],
    },
    {
      key: "crown",
      title: "Crown treatment",
      weight: 1.6,
      quote: true,
      lines: [
        { sku: "BUILDUP", qty: [1, 1], p: 0.7 },
        { sku: "CROWN-ZR", qty: [1, 1] },
      ],
      visits: 2,
      visitTitles: ["Crown — preparation visit", "Crown — seat visit"],
      durationMin: [60, 90],
      crew: ["dentist"],
      billing: "on-completion",
      leadTimeDays: [5, 14],
      requests: [
        "Dr. said at my last cleaning that I need a crown on a cracked tooth. Can you send me the cost estimate?",
        "I'd like to schedule the crown we talked about. What will insurance cover?",
      ],
      repeatRequests: [
        "At my last cleaning the doctor said I need a crown on a cracked tooth. Can you send me the cost estimate?",
        "I'd like to go ahead with the crown we talked about at my last visit. What will insurance cover?",
      ],
    },
    {
      key: "root-canal",
      title: "Root canal and crown",
      weight: 0.8,
      quote: true,
      lines: [
        { sku: "RCT-MOLAR", qty: [1, 1] },
        { sku: "BUILDUP", qty: [1, 1] },
        { sku: "CROWN-ZR", qty: [1, 1] },
      ],
      visits: 2,
      visitTitles: ["Root canal visit", "Crown seat visit"],
      durationMin: [75, 120],
      crew: ["dentist"],
      billing: "on-completion",
      leadTimeDays: [3, 10],
      requests: ["I was told I need a root canal on a back molar. What's the out-of-pocket cost and how many visits?"],
      repeatRequests: ["The doctor said at my last visit that I'll need a root canal on that back molar. What's the out-of-pocket cost?"],
    },
    {
      key: "perio",
      title: "Periodontal therapy",
      weight: 0.9,
      quote: true,
      lines: [{ sku: "SRP-QUAD", qty: [2, 4] }],
      visits: 2,
      visitTitles: ["Scaling and root planing, visit 1", "Scaling and root planing, visit 2"],
      durationMin: [60, 90],
      crew: ["hygienist"],
      billing: "on-completion",
      leadTimeDays: [5, 14],
      requests: ["My gums bleed when I brush and the hygienist mentioned deep cleaning. Can I get a plan and price?"],
      repeatRequests: ["My hygienist recommended a deep cleaning at my last appointment. Can I get the plan and price?"],
    },
    {
      key: "whitening",
      title: "In-office whitening",
      weight: 0.8,
      quote: true,
      lines: [{ sku: "WHITEN", qty: [1, 1] }],
      durationMin: [90, 90],
      crew: ["hygienist"],
      billing: "on-completion",
      leadTimeDays: [3, 21],
      requests: ["I have a wedding in two months. How much is professional whitening and how long does it take?"],
      repeatRequests: ["I'm already a patient and I have a wedding in two months. Could I add whitening, and what does it cost?"],
    },
    {
      key: "night-guard",
      title: "Custom night guard",
      weight: 0.6,
      quote: true,
      lines: [{ sku: "NIGHTGUARD", qty: [1, 1] }],
      visits: 2,
      visitTitles: ["Night guard impressions", "Night guard delivery"],
      durationMin: [30, 30],
      crew: ["dentist"],
      billing: "on-completion",
      leadTimeDays: [3, 14],
      requests: ["I grind my teeth at night and wake up with jaw pain. Do you make custom night guards?"],
      repeatRequests: ["The doctor mentioned a night guard at my last checkup because I grind my teeth. I'd like to go ahead. What's the cost?"],
    },
  ],
  sourceWeights: { phone: 5, "web-form": 4, referral: 3, "google-ads": 2, "walk-in": 1 },
  paymentMethods: { card: 7, cash: 1, check: 1 },
  existingShare: 0.55,
  recurringShare: 0.85,
  recurringOffering: "hygiene-recall",
  repeatRate: 0.45,
  bookedAhead: {
    rate: 0.35,
    visits: [
      { title: "Hygiene visit and periodic exam", weight: 5, durationMin: [60, 60], crew: ["hygienist", "dentist"], forPlan: true },
      { title: "Periodic exam and cleaning", weight: 2, durationMin: [60, 60], crew: ["hygienist"] },
      { title: "Filling appointment", weight: 2, durationMin: [30, 60], crew: ["dentist"] },
      { title: "Follow-up exam", weight: 1, durationMin: [30, 30], crew: ["dentist"] },
    ],
  },
  contactTitles: [],
  tags: ["ppo", "self-pay", "family-plan", "prefers-mornings", "anxious-patient", "text-reminders"],
  replyLines: [
    "We'd be glad to see you. We have openings next week — would a morning or afternoon visit work better?",
    "Thanks for reaching out! Please bring your insurance card and a photo ID to your first visit.",
    "We can help with that. I'm holding a couple of times for you; reply or call and we'll lock one in.",
  ],
  disqualifyReasons: [
    "Looking for an orthodontist for braces",
    "Insurance plan is out of network and patient declined self-pay",
    "Was trying to reach a different practice",
  ],
  lostReasons: ["Insurance coverage too low", "Chose to postpone treatment", "Getting a second opinion", "Moved out of the area"],
  acceptTexts: [
    "Thanks for sending the plan. I'd like to go ahead — what times do you have?",
    "That works with my budget. Please book me in.",
    "OK, let's schedule it. Afternoons are easiest for me.",
  ],
  declineTexts: [
    "I'm going to wait until my insurance resets in January.",
    "I want to get a second opinion before deciding. Thanks.",
    "That's more than I can do right now, so I'll hold off.",
  ],
  questionTexts: [
    "Can I split the treatment across two calendar years for insurance?",
    "Do you offer a payment plan for the patient portion?",
    "Is the estimate before or after insurance?",
  ],
  quoteNote: "Estimated fees shown before insurance. Your insurance plan may cover part of this; we'll file the claim and bill any patient portion after.",
  confirmNote: "Please arrive 10 minutes early.",
  invoiceNote: "This statement reflects the patient portion after estimated insurance. Call the front desk with any questions.",
  recallText: "Hi {first}, you're due for your 6-month cleaning and exam. We have openings around {when} — reply to grab a time.",
  voicemails: [
    "Hi, I'm calling to see if you're taking new patients. Please call me back.",
    "Hi, I have a question about my bill. Can someone return my call? Thanks.",
    "Hello, I'd like to make an appointment for a cleaning. Call me back please.",
    "Hi, I think I cracked a tooth. Please call me back as soon as possible.",
  ],
  customerQuestions: [
    "Can you email me a receipt for my last visit for my HSA?",
    "Do I need to fill out new forms before my next appointment?",
    "What time is my next appointment again?",
    "Has my insurance claim from the last visit been processed?",
  ],
  questionReplies: [
    "Of course! I've sent that over by email.",
    "Thanks for checking — you're all set, nothing else needed.",
    "Good question. I've checked your account and will call you with details today.",
  ],
  jobNotes: [
    "Estimated insurance coverage: preventive at 100%, patient portion billed after claim.",
    "Patient prefers text reminders.",
    "Patient is nervous — allow extra time.",
    "Insurance verification pending at time of booking.",
  ],
};
