import type { IndustryProfile } from "./types.js";

export const homeServices: IndustryProfile = {
  id: "home-services",
  name: "Home services (HVAC & plumbing)",
  summary:
    "Residential HVAC and plumbing contractor: households, service calls, equipment installs and maintenance plans.",
  companyNames: [
    "Bluestem Heating & Plumbing",
    "Copper Kettle Plumbing & Air",
    "Northgate Comfort Co.",
    "Brightline Home Services",
    "Fernway Heating & Cooling",
    "Two Rivers Plumbing & Air",
    "Lantern Hill Mechanical",
    "Steadfast Comfort Pros",
  ],
  companyDescription: "Residential HVAC and plumbing: repairs, replacements and maintenance plans",
  customerKind: "household",
  nouns: { quote: "estimate", job: "service visit", customer: "customer" },
  quotePrefix: "Q-",
  quoteValidDays: 30,
  paymentTermsDays: 15,
  openDays: [1, 2, 3, 4, 5, 6],
  roster: [
    { role: "owner", small: 1, medium: 1, large: 1 },
    { role: "office-manager", small: 1, medium: 1, large: 1 },
    { role: "dispatcher", small: 0, medium: 1, large: 2 },
    { role: "sales", small: 0, medium: 1, large: 2 },
    { role: "technician", small: 2, medium: 4, large: 9 },
    { role: "bookkeeper", small: 0, medium: 1, large: 1 },
  ],
  salesRoles: ["sales", "owner"],
  schedulerRoles: ["dispatcher", "office-manager"],
  policies: [
    { title: "Diagnostic fee", rule: "Diagnostic visits are $129 and are credited toward any repair the customer approves the same day." },
    { title: "Estimate validity", rule: "Written estimates are valid for 30 days from the date they are sent." },
    { title: "Priority service", rule: "No-heat calls below 32°F and no-cooling calls above 90°F get same-day priority dispatch." },
    { title: "Payment terms", rule: "Invoices are due within 15 days of completion; card, ACH and check are accepted." },
    { title: "Comfort Club", rule: "Maintenance-plan members get two tune-ups per year and are recalled every 6 months." },
    { title: "Appointment changes", rule: "Text the customer the same day an appointment is booked or moved, and update the technician's task to the new time." },
  ],
  catalog: [
    { sku: "DIAG-SVC", description: "Diagnostic service call", unitPriceCents: 12900 },
    { sku: "HVAC-TUNE", description: "Heating/cooling tune-up (21-point inspection)", unitPriceCents: 14900 },
    { sku: "MEMB-PLAN", description: "Comfort Club maintenance plan, 12 months", unitPriceCents: 21900 },
    { sku: "CAP-RPL", description: "Run capacitor replacement", unitPriceCents: 18500 },
    { sku: "IGN-RPL", description: "Furnace hot-surface igniter replacement", unitPriceCents: 26500 },
    { sku: "REFRIG-LB", description: "Refrigerant recharge (per lb)", unitPriceCents: 9500 },
    { sku: "AC-INST-3T", description: "3-ton 16 SEER2 AC condenser and coil, installed", unitPriceCents: 785000 },
    { sku: "FURN-INST-96", description: "96% AFUE gas furnace, installed", unitPriceCents: 540000 },
    { sku: "HP-INST", description: "Ducted heat pump system, installed", unitPriceCents: 1190000 },
    { sku: "WH-50G", description: "50-gallon gas water heater, installed", unitPriceCents: 189500 },
    { sku: "WH-TANKLESS", description: "Tankless gas water heater, installed", unitPriceCents: 385000 },
    { sku: "THERMO-SMART", description: "Smart thermostat, installed", unitPriceCents: 34900 },
    { sku: "PERMIT", description: "Municipal mechanical/plumbing permit", unitPriceCents: 15000 },
    { sku: "HAUL-AWAY", description: "Removal and disposal of old equipment", unitPriceCents: 12500 },
    { sku: "PLMB-HR", description: "Plumbing repair labor (per hour)", unitPriceCents: 14500 },
    { sku: "DRAIN-MAIN", description: "Main sewer line drain clearing", unitPriceCents: 28900 },
    { sku: "PARTS-PLMB", description: "Plumbing parts and fittings", unitPriceCents: 4800 },
    { sku: "DUCT-SEAL", description: "Duct sealing (per run)", unitPriceCents: 9500 },
  ],
  offerings: [
    {
      key: "no-cool-heat",
      title: "No heat / no cooling service call",
      weight: 4,
      quote: false,
      lines: [
        { sku: "DIAG-SVC", qty: [1, 1] },
        { sku: "CAP-RPL", qty: [1, 1], p: 0.45 },
        { sku: "IGN-RPL", qty: [1, 1], p: 0.25 },
        { sku: "REFRIG-LB", qty: [1, 3], p: 0.3 },
      ],
      durationMin: [60, 150],
      crew: ["technician"],
      billing: "on-completion",
      leadTimeDays: [1, 2],
      requests: [
        "Our AC is running but blowing warm air and the house is at 84 degrees. Can someone come out today or tomorrow?",
        "Furnace keeps clicking and won't light. We have a newborn at home so I'd like to get this fixed fast.",
        "The outdoor unit is humming but the fan isn't spinning. Is that something you can look at this week?",
        "Heat pump is making a grinding noise and the upstairs is freezing. What's your next opening?",
        "Thermostat says cooling but nothing happens. Already changed the batteries.",
      ],
      repeatRequests: [
        "Hi, it's us again. The AC you looked at last time is blowing warm air now. Could someone come out this week?",
        "Our furnace won't light again. Your tech fixed it before, so we'd like the same person if we can.",
        "The heat pump you serviced is making a grinding noise. What's your next opening?",
      ],
    },
    {
      key: "plumbing-repair",
      title: "Plumbing leak / drain repair",
      weight: 3,
      quote: false,
      lines: [
        { sku: "PLMB-HR", qty: [1, 3] },
        { sku: "PARTS-PLMB", qty: [1, 4] },
        { sku: "DRAIN-MAIN", qty: [1, 1], p: 0.3 },
      ],
      durationMin: [60, 180],
      crew: ["technician"],
      billing: "on-completion",
      leadTimeDays: [1, 3],
      requests: [
        "There's water dripping from the ceiling under our upstairs bathroom. Can you send a plumber?",
        "Kitchen sink and the basement floor drain are both backing up. I think it's the main line.",
        "Toilet keeps running and the shutoff valve under it is leaking now too.",
        "Low water pressure in the whole house since last week, plus a damp spot near the water meter.",
      ],
      repeatRequests: [
        "You fixed our kitchen drain a while back. Now the upstairs shower is draining slowly. Can you send someone?",
        "Hi, it's us again. There's a new leak under the bathroom sink. Can a plumber come by this week?",
      ],
    },
    {
      key: "ac-replacement",
      title: "AC system replacement",
      weight: 2.6,
      quote: true,
      lines: [
        { sku: "AC-INST-3T", qty: [1, 1] },
        { sku: "PERMIT", qty: [1, 1] },
        { sku: "HAUL-AWAY", qty: [1, 1] },
        { sku: "THERMO-SMART", qty: [1, 1], p: 0.5 },
        { sku: "DUCT-SEAL", qty: [2, 6], p: 0.35 },
      ],
      durationMin: [420, 480],
      crew: ["technician", "technician"],
      billing: "on-completion",
      leadTimeDays: [3, 10],
      requests: [
        "Our AC is 19 years old and the last tech said the compressor is going. Could we get a replacement estimate?",
        "Looking for a quote to replace our central air before next summer. About 1,900 sq ft, two stories.",
        "We just bought the house and the AC barely keeps up. Can someone give us replacement options?",
      ],
      repeatRequests: [
        "Your tech said our AC was near the end of its life the last time he was out. We're ready for a replacement quote.",
        "We've used you for repairs for years. Time to replace the old central air. Can you send over options?",
      ],
    },
    {
      key: "furnace-replacement",
      title: "Furnace replacement",
      weight: 1.8,
      quote: true,
      lines: [
        { sku: "FURN-INST-96", qty: [1, 1] },
        { sku: "PERMIT", qty: [1, 1] },
        { sku: "HAUL-AWAY", qty: [1, 1] },
        { sku: "THERMO-SMART", qty: [1, 1], p: 0.4 },
      ],
      durationMin: [360, 480],
      crew: ["technician", "technician"],
      billing: "on-completion",
      leadTimeDays: [3, 10],
      requests: [
        "Furnace is original to the house (1998) and the heat exchanger has a crack per our last inspection. Need an estimate.",
        "We'd like a quote on a high-efficiency furnace. Our gas bills have been brutal.",
      ],
      repeatRequests: [
        "Your tech flagged our furnace at the last tune-up. We'd like an estimate on a replacement before winter.",
        "We've had you out for the furnace a couple of times now. Can you quote a new high-efficiency unit?",
      ],
    },
    {
      key: "heat-pump",
      title: "Heat pump conversion",
      weight: 1,
      quote: true,
      lines: [
        { sku: "HP-INST", qty: [1, 1] },
        { sku: "PERMIT", qty: [1, 1] },
        { sku: "HAUL-AWAY", qty: [1, 1] },
        { sku: "THERMO-SMART", qty: [1, 1] },
      ],
      durationMin: [480, 480],
      crew: ["technician", "technician"],
      billing: "on-completion",
      leadTimeDays: [5, 14],
      requests: [
        "Interested in replacing our furnace and AC with a heat pump. Do you do those, and what would it cost roughly?",
      ],
      repeatRequests: [
        "You've serviced our furnace and AC before. We're thinking about switching to a heat pump. What would that cost?",
      ],
    },
    {
      key: "water-heater",
      title: "Water heater replacement",
      weight: 2.6,
      quote: true,
      lines: [
        { sku: "WH-50G", qty: [1, 1], p: 0.7, group: "heater" },
        { sku: "WH-TANKLESS", qty: [1, 1], p: 0.3, group: "heater" },
        { sku: "PERMIT", qty: [1, 1] },
        { sku: "HAUL-AWAY", qty: [1, 1] },
      ],
      durationMin: [180, 300],
      crew: ["technician"],
      billing: "on-completion",
      leadTimeDays: [1, 5],
      requests: [
        "Water heater is leaking from the bottom and we have no hot water. Need a replacement quote ASAP.",
        "Our 12-year-old water heater is making popping sounds. Thinking about going tankless — can you quote both?",
      ],
      repeatRequests: [
        "Hi, it's us again. Our water heater is leaking now. Can you quote a replacement like the one you mentioned last visit?",
        "Your plumber said our water heater was getting old. It's making popping sounds now. Can we get a tankless quote too?",
      ],
    },
    {
      key: "maintenance-plan",
      title: "Comfort Club signup + tune-up",
      weight: 1.4,
      quote: false,
      lines: [
        { sku: "MEMB-PLAN", qty: [1, 1] },
        { sku: "HVAC-TUNE", qty: [1, 1] },
      ],
      durationMin: [60, 90],
      crew: ["technician"],
      billing: "on-completion",
      recurring: { everyMonths: 6, offering: "plan-tuneup" },
      leadTimeDays: [2, 7],
      requests: [
        "I saw you have a maintenance plan. We'd like to sign up and get the furnace checked before winter.",
        "Can we schedule a tune-up for the AC? Also interested in the yearly plan if it covers two visits.",
      ],
      repeatRequests: [
        "You did a great job on our last repair. We'd like to join the Comfort Club and get a tune-up booked.",
        "We've been customers for a while. Can we sign up for the maintenance plan and schedule the first visit?",
      ],
    },
    {
      key: "plan-tuneup",
      title: "Comfort Club seasonal tune-up",
      weight: 0,
      quote: false,
      lines: [
        { sku: "HVAC-TUNE", qty: [1, 1] },
        { sku: "CAP-RPL", qty: [1, 1], p: 0.15 },
      ],
      durationMin: [60, 90],
      crew: ["technician"],
      billing: "on-completion",
      leadTimeDays: [2, 10],
      requests: ["Time for our seasonal tune-up."],
    },
  ],
  sourceWeights: { "web-form": 4, phone: 5, referral: 2, "google-ads": 3, email: 1 },
  paymentMethods: { card: 6, check: 3, ach: 1 },
  existingShare: 0.45,
  recurringShare: 0.5,
  recurringOffering: "plan-tuneup",
  repeatRate: 0.6,
  bookedAhead: {
    rate: 0.25,
    visits: [
      { title: "Comfort Club seasonal tune-up", weight: 3, durationMin: [60, 90], crew: ["technician"], forPlan: true },
      { title: "No heat / no cooling service call", weight: 3, durationMin: [60, 150], crew: ["technician"] },
      { title: "Plumbing leak / drain repair", weight: 2, durationMin: [60, 180], crew: ["technician"] },
      { title: "Seasonal HVAC tune-up", weight: 2, durationMin: [60, 90], crew: ["technician"] },
      { title: "Water heater flush and inspection", weight: 1, durationMin: [60, 90], crew: ["technician"] },
    ],
  },
  contactTitles: [],
  tags: ["residential", "single-family", "townhome", "warranty", "pets-on-site", "gate-code"],
  replyLines: [
    "We can get a technician out to take a look. Does tomorrow morning or Thursday afternoon work better?",
    "Thanks for the details. I'd like to get eyes on it in person — we have openings later this week.",
    "Sorry you're dealing with that. Our dispatcher can fit you in; what's the best number to reach you?",
  ],
  disqualifyReasons: [
    "Outside our service area",
    "Commercial rooftop unit — we only service residential",
    "Was looking for an appliance repair shop",
  ],
  lostReasons: ["Went with a lower bid", "Decided to repair instead of replace", "Financing not approved", "Chose another contractor"],
  acceptTexts: [
    "Thanks — we'd like to go ahead with the estimate. What's your first available install date?",
    "Approved. Please schedule us as soon as you can.",
    "We talked it over and want to move forward. Mornings are best for us.",
  ],
  declineTexts: [
    "Thanks for the estimate, but we're going to hold off until next year.",
    "We got another quote that came in lower, so we'll pass for now.",
    "We decided to try a repair first. Appreciate your time.",
  ],
  questionTexts: [
    "Does the price include the permit and hauling away the old unit?",
    "Is there any financing available, or a discount if we sign up for the maintenance plan?",
    "What warranty comes with the equipment and the labor?",
  ],
  quoteNote: "Price includes labor, permit and haul-away where listed. 10-year parts and 2-year labor warranty on installed equipment.",
  confirmNote: "Your technician will text when on the way.",
  invoiceNote: "Questions about this invoice? Just reply to this email.",
  recallText: "Hi {first}, it's time for your Comfort Club tune-up. Reply with a day that works and we'll get you on the schedule (we have openings around {when}).",
  voicemails: [
    "Hi, this is about a leak under my kitchen sink. Please call me back when you can.",
    "Hey, our AC stopped working this morning and it's getting hot in here. Give me a call back, thanks.",
    "Calling to get a price on a new water heater. Call me back please.",
    "Hi, I wanted to ask if you service tankless water heaters. Thanks.",
  ],
  customerQuestions: [
    "Quick question — what filter size should we be using for our furnace?",
    "Can you send me a copy of my last invoice for our records?",
    "Is my Comfort Club membership still active?",
    "The tech mentioned a warranty registration. Did that get submitted?",
  ],
  questionReplies: [
    "Happy to help! I've sent that over — let us know if you need anything else.",
    "Good question. I checked your file and you're all set.",
    "Thanks for asking — I'll have the technician follow up with details today.",
  ],
  jobNotes: [
    "Dog in backyard — call before entering gate.",
    "Park in the driveway, side door entrance.",
    "Customer prefers text updates.",
    "Attic access through hallway closet.",
  ],
};
