import type { IndustryProfile } from "./types.js";

export const marketingAgency: IndustryProfile = {
  id: "marketing-agency",
  name: "Marketing agency",
  summary:
    "Small digital marketing agency: business clients, proposals, website and brand projects, and monthly retainers.",
  companyNames: [
    "Lanternfish Creative",
    "North Pier Marketing",
    "Fieldnote Studio",
    "Tidewater Digital",
    "Paper Kite Agency",
    "Bright Signal Marketing",
  ],
  companyDescription: "Digital marketing for local businesses: websites, branding, SEO, social and paid search",
  customerKind: "business",
  nouns: { quote: "proposal", job: "project", customer: "client" },
  quotePrefix: "P-",
  quoteValidDays: 21,
  paymentTermsDays: 30,
  openDays: [1, 2, 3, 4, 5],
  roster: [
    { role: "owner", small: 1, medium: 1, large: 1 },
    { role: "account-manager", small: 1, medium: 2, large: 4 },
    { role: "strategist", small: 0, medium: 1, large: 2 },
    { role: "designer", small: 1, medium: 2, large: 4 },
    { role: "bookkeeper", small: 0, medium: 1, large: 1 },
  ],
  salesRoles: ["owner", "account-manager"],
  schedulerRoles: ["account-manager"],
  policies: [
    { title: "Proposal validity", rule: "Proposals are valid for 21 days from the date sent." },
    { title: "Project billing", rule: "Projects are billed 50% at signing and 50% at launch." },
    { title: "Retainers", rule: "Retainers are billed monthly in advance for the committed term." },
    { title: "Payment terms", rule: "All invoices are net 30." },
    { title: "Response time", rule: "Reply to client emails within one business day." },
    { title: "Change orders", rule: "Out-of-scope work needs a written change order before anyone starts on it." },
  ],
  catalog: [
    { sku: "STRAT-WS", description: "Brand and marketing strategy workshop", unitPriceCents: 350000 },
    { sku: "WEB-DESIGN", description: "Website page template design", unitPriceCents: 120000 },
    { sku: "WEB-DEV", description: "Website page build (CMS)", unitPriceCents: 65000 },
    { sku: "SEO-AUDIT", description: "Technical SEO audit", unitPriceCents: 180000 },
    { sku: "RET-SEO", description: "SEO retainer (monthly)", unitPriceCents: 250000 },
    { sku: "RET-SOCIAL", description: "Social media management (monthly)", unitPriceCents: 195000 },
    { sku: "RET-PPC", description: "Paid search management (monthly)", unitPriceCents: 160000 },
    { sku: "AD-SETUP", description: "Ad account setup and tracking", unitPriceCents: 90000 },
    { sku: "CONTENT-BLOG", description: "Blog article, ~1,200 words", unitPriceCents: 35000 },
    { sku: "PHOTO-DAY", description: "On-site photo shoot (day)", unitPriceCents: 220000 },
    { sku: "LOGO-ID", description: "Logo and visual identity package", unitPriceCents: 480000 },
  ],
  offerings: [
    {
      key: "website",
      title: "Website redesign",
      weight: 2,
      quote: true,
      lines: [
        { sku: "STRAT-WS", qty: [1, 1], p: 0.5 },
        { sku: "WEB-DESIGN", qty: [3, 6] },
        { sku: "WEB-DEV", qty: [8, 20] },
        { sku: "PHOTO-DAY", qty: [1, 1], p: 0.3 },
      ],
      durationDays: [42, 75],
      milestones: ["Website kickoff meeting", "Website design review", "Website launch review"],
      durationMin: [60, 90],
      crew: ["account-manager", "designer", "strategist"],
      billing: "deposit-and-final",
      leadTimeDays: [5, 15],
      requests: [
        "Our website is about eight years old and doesn't work well on phones. We'd like a proposal for a redesign.",
        "We're opening a second location and need a site that can handle online booking. Can we talk about a rebuild?",
        "Looking for an agency to redo our website. Budget is flexible for the right team.",
      ],
      repeatRequests: [
        "You did our branding last year and we loved it. Now our website needs the same treatment. Can you send a proposal?",
        "We're opening a second location and our current site can't handle online booking. Can we talk about a rebuild with your team?",
      ],
    },
    {
      key: "brand",
      title: "Brand identity",
      weight: 1,
      quote: true,
      lines: [
        { sku: "STRAT-WS", qty: [1, 1] },
        { sku: "LOGO-ID", qty: [1, 1] },
      ],
      durationDays: [28, 45],
      milestones: ["Brand discovery workshop", "Brand concept presentation", "Brand guidelines handoff"],
      durationMin: [60, 120],
      crew: ["account-manager", "designer"],
      billing: "deposit-and-final",
      leadTimeDays: [5, 15],
      requests: [
        "We're rebranding after a merger and need a new logo and brand guidelines.",
        "Our logo was made by a friend years ago. Time for something professional — what would that cost?",
      ],
      repeatRequests: [
        "We've liked working with you on our marketing. We're rebranding after a merger. Could you scope a new identity?",
      ],
    },
    {
      key: "seo-retainer",
      title: "SEO retainer",
      weight: 2,
      quote: true,
      lines: [
        { sku: "SEO-AUDIT", qty: [1, 1] },
        { sku: "RET-SEO", qty: [6, 12] },
      ],
      crew: ["strategist", "account-manager"],
      billing: "monthly",
      monthlySku: "RET-SEO",
      termMonths: [6, 12],
      milestones: ["SEO kickoff meeting", "Monthly SEO performance review"],
      durationMin: [45, 60],
      leadTimeDays: [3, 12],
      requests: [
        "We don't show up on Google for anything except our own name. Interested in ongoing SEO help.",
        "A competitor outranks us for every local search. Can you put together an SEO plan and monthly pricing?",
      ],
      repeatRequests: [
        "Now that the new site is live, we'd like you to handle SEO on an ongoing basis. Can you send monthly pricing?",
        "Our previous SEO term with you ended and rankings are slipping. Can we restart a retainer?",
      ],
    },
    {
      key: "social-retainer",
      title: "Social media management",
      weight: 1.5,
      quote: true,
      lines: [
        { sku: "RET-SOCIAL", qty: [3, 12] },
        { sku: "PHOTO-DAY", qty: [1, 1], p: 0.4 },
      ],
      crew: ["designer", "account-manager"],
      billing: "monthly",
      monthlySku: "RET-SOCIAL",
      termMonths: [3, 12],
      milestones: ["Social media kickoff meeting", "Monthly social content review"],
      durationMin: [45, 60],
      leadTimeDays: [3, 12],
      requests: [
        "We post on Instagram maybe once a month. Looking for someone to manage our social accounts.",
        "Can you quote social media management for Facebook, Instagram and LinkedIn?",
      ],
      repeatRequests: [
        "We'd like to add social media management to the work you already do for us. Can you quote Facebook and Instagram?",
      ],
    },
    {
      key: "ppc",
      title: "Paid search launch",
      weight: 1,
      quote: true,
      lines: [
        { sku: "AD-SETUP", qty: [1, 1] },
        { sku: "RET-PPC", qty: [3, 6] },
      ],
      crew: ["strategist"],
      billing: "monthly",
      monthlySku: "RET-PPC",
      termMonths: [3, 6],
      milestones: ["Paid search kickoff meeting", "Monthly paid search review"],
      durationMin: [45, 60],
      leadTimeDays: [3, 10],
      requests: [
        "We tried running Google Ads ourselves and wasted a lot of money. Can you manage them for us?",
      ],
      repeatRequests: ["You've been great on our other marketing. Could you take over our Google Ads too?"],
    },
    {
      key: "content",
      title: "Content package",
      weight: 1,
      quote: true,
      lines: [{ sku: "CONTENT-BLOG", qty: [6, 12] }],
      durationDays: [30, 60],
      milestones: ["Content planning session", "Content draft review", "Content final review"],
      durationMin: [45, 60],
      crew: ["strategist"],
      billing: "on-completion",
      leadTimeDays: [3, 10],
      requests: ["We need a batch of blog articles for our website. What do you charge per article?"],
      repeatRequests: ["We'd like another batch of blog articles like the last ones you wrote for us. Can you quote it?"],
    },
  ],
  sourceWeights: { referral: 5, "web-form": 3, email: 2, "google-ads": 1, phone: 1 },
  paymentMethods: { ach: 6, check: 3, card: 2 },
  existingShare: 0.35,
  recurringShare: 0,
  recurringOffering: null,
  repeatRate: 1.0,
  bookedAhead: {
    rate: 0.15,
    visits: [
      { title: "Quarterly strategy review", weight: 3, durationMin: [60, 90], crew: ["account-manager", "strategist"] },
      { title: "Deliverable review", weight: 3, durationMin: [45, 60], crew: ["account-manager", "designer"] },
      { title: "Monthly reporting call", weight: 2, durationMin: [30, 45], crew: ["account-manager"] },
    ],
  },
  contactTitles: ["Owner", "Marketing Director", "Office Manager", "General Manager", "Co-founder", "Operations Lead"],
  tags: ["b2b", "local-business", "multi-location", "nonprofit-rate", "referral-partner", "net-30"],
  replyLines: [
    "I'd love to set up a 30-minute discovery call to learn about your goals. Are you free Thursday or Friday?",
    "Great to hear from you. Could you share a couple of competitors you admire and your rough timeline? Then we'll put a proposal together.",
    "Happy to help. I'll send a short questionnaire so we can scope this properly.",
  ],
  disqualifyReasons: [
    "Budget below our minimum engagement",
    "Needs a full in-house marketing hire, not an agency",
    "Looking for a printing vendor",
  ],
  lostReasons: ["Went with a freelancer", "Budget cut for the quarter", "Chose a larger agency", "Project put on hold"],
  acceptTexts: [
    "We've reviewed the proposal and we're in. Send over whatever you need to get started.",
    "Approved — let's kick off. Who should our team expect to hear from?",
    "Looks great. Signed copy attached; please send the first invoice.",
  ],
  declineTexts: [
    "Thanks for the thorough proposal. We've decided to keep this in-house for now.",
    "The scope is more than we can take on this quarter. Let's revisit in the spring.",
    "We went with another agency, but we appreciate your time.",
  ],
  questionTexts: [
    "Could we phase the work to spread out the cost?",
    "Is hosting included, or is that separate?",
    "What does reporting look like each month?",
  ],
  quoteNote: "Pricing assumes two rounds of revisions per deliverable. Retainer terms renew month-to-month after the committed period.",
  confirmNote: "Calendar invite with the video link to follow.",
  invoiceNote: "ACH details are on the invoice. Net 30.",
  recallText: "Hi {first}, checking in ahead of {when}.",
  voicemails: [
    "Hi, I got your name from a friend and I'm looking for help with our website. Please call me back.",
    "Hi, this is about getting a quote for social media management. Call me when you get a chance.",
    "Hello, I'd like to talk to someone about Google Ads for my business. Thanks.",
  ],
  customerQuestions: [
    "Can you resend last month's performance report? I can't find it.",
    "We have a promotion next week — can you add a post about it?",
    "Who should I send our new photos to?",
    "Could you update the hours on our Google listing?",
  ],
  questionReplies: [
    "Absolutely — I've sent it over and copied your team.",
    "Done! It's scheduled and I'll confirm once it's live.",
    "Thanks for the heads-up. We'll take care of it today.",
  ],
  jobNotes: [
    "Client prefers Tuesday status calls.",
    "Brand assets in shared drive; approvals by the owner only.",
    "Weekly report every Monday.",
    "Legal must review any claims in ad copy.",
  ],
};
