import { homeServices } from "./home-services.js";
import type { IndustryProfile } from "./types.js";

/** Fictional independent dealer using the existing quote/job/payment storylines. */
export const trailerDealer: IndustryProfile = {
  ...homeServices,
  id: "trailer-dealer",
  name: "Trailer dealer",
  summary: "Independent utility, cargo and equipment trailer sales, hitch installation and servicing.",
  companyNames: ["Coppertrail Trailer Sales", "Lantern Ridge Trailer Works", "Bluestem Cargo Trailers", "Fernway Trailer Depot"],
  companyDescription: "Trailer sales, customer pickup, hitch installation and brake/bearing service",
  nouns: { quote: "quote", job: "work order", customer: "customer" },
  policies: [
    { title: "Sale approval", rule: "A written customer-approved quote is required before preparing a trailer for pickup." },
    { title: "Service approval", rule: "Additional parts or repair work requires customer approval before installation." },
    { title: "Payment terms", rule: "Service invoices are due within 15 days. Trailer sales use a deposit and final payment." },
    { title: "Safety inspection", rule: "Check lights, tire pressure, bearings and coupler before customer pickup." },
  ],
  catalog: [
    { sku: "UTILITY-6X12", description: "6x12 utility trailer", unitPriceCents: 279500 },
    { sku: "CARGO-7X16", description: "7x16 enclosed cargo trailer", unitPriceCents: 849500 },
    { sku: "EQUIPMENT-7X20", description: "7x20 equipment trailer", unitPriceCents: 1099500 },
    { sku: "HITCH-INSTALL", description: "Receiver hitch installation", unitPriceCents: 45900 },
    { sku: "BRAKE-SVC", description: "Trailer brake inspection and adjustment", unitPriceCents: 18900 },
    { sku: "BEARING-SVC", description: "Trailer bearing inspection and repack", unitPriceCents: 24900 },
    { sku: "LIGHT-REPAIR", description: "Trailer lighting repair", unitPriceCents: 12900 },
  ],
  offerings: [
    { key: "trailer-sale", title: "Trailer sale and pickup", weight: 4, quote: true,
      lines: [{ sku: "UTILITY-6X12", qty: [1, 1], group: "trailer", p: 4 }, { sku: "CARGO-7X16", qty: [1, 1], group: "trailer", p: 3 }, { sku: "EQUIPMENT-7X20", qty: [1, 1], group: "trailer", p: 2 }],
      durationMin: [60, 90], crew: ["sales", "technician"], billing: "deposit-and-final", leadTimeDays: [2, 14],
      repeatRequests: ["We bought a trailer from you before and need another for our crew."],
      requests: ["I need a utility trailer for landscaping equipment. Can you quote one ready for pickup?", "We need an enclosed cargo trailer for tools. What is available this month?", "Can you quote an equipment trailer and walk us through pickup safety checks?"] },
    { key: "hitch-install", title: "Receiver hitch installation", weight: 2, quote: true,
      lines: [{ sku: "HITCH-INSTALL", qty: [1, 1] }], durationMin: [90, 180], crew: ["technician"], billing: "on-completion", leadTimeDays: [2, 7],
      repeatRequests: ["You fitted our last hitch. Can you help fit one to our new towing vehicle?"],
      requests: ["Can you fit a receiver hitch and check the trailer light connection?"] },
    { key: "trailer-service", title: "Trailer brake and bearing service", weight: 3, quote: false,
      lines: [{ sku: "BRAKE-SVC", qty: [1, 1] }, { sku: "BEARING-SVC", qty: [1, 1] }, { sku: "LIGHT-REPAIR", qty: [1, 1], p: 0.3 }],
      durationMin: [60, 150], crew: ["technician"], billing: "on-completion", leadTimeDays: [1, 5],
      repeatRequests: ["Our trailer you serviced last year is due for another brake and bearing check."],
      requests: ["The trailer brakes feel uneven. Can you inspect them and the bearings?"],
      recurring: { everyMonths: 12, offering: "annual-inspection" } },
    { key: "annual-inspection", title: "Annual trailer safety inspection", weight: 0, quote: false,
      lines: [{ sku: "BRAKE-SVC", qty: [1, 1] }, { sku: "BEARING-SVC", qty: [1, 1] }],
      durationMin: [60, 120], crew: ["technician"], billing: "on-completion", leadTimeDays: [2, 7],
      requests: ["Our trailer is due for its annual brake and bearing inspection."] },
  ],
  recurringOffering: "annual-inspection",
  bookedAhead: { rate: 0.3, visits: [{ title: "Trailer safety inspection", weight: 1, durationMin: [60, 90], crew: ["technician"] }] },
  tags: ["utility", "cargo", "equipment", "repeat-service"],
  replyLines: ["Thanks for contacting us. We can arrange a trailer inspection or prepare a written quote.", "Please bring the trailer details and your towing vehicle information to the appointment."],
  disqualifyReasons: ["Outside our trailer service scope", "Customer requested a product we do not stock"],
  lostReasons: ["Purchased elsewhere", "Deferred trailer purchase", "Selected another service shop"],
  acceptTexts: ["Please go ahead with the quoted trailer and arrange pickup.", "I approve the service quote. Please book the trailer in."],
  declineTexts: ["We are postponing the trailer purchase.", "We chose another service shop. Thank you for the quote."],
  questionTexts: ["Does the quote include the hitch fitting and pickup safety check?", "When can I drop off the trailer for service?"],
  quoteNote: "Only the listed trailer, accessories and approved service are included.",
  confirmNote: "Bring the trailer and towing vehicle details to your appointment.",
  invoiceNote: "Questions about this trailer invoice? Reply to this email.",
  recallText: "Hi {first}, your trailer is due for its annual safety inspection. Reply with a day near {when}.",
  voicemails: ["Please call me about a cargo trailer quote.", "The trailer lights are intermittent. Can I book an inspection?"],
  customerQuestions: ["Can you send a copy of my trailer invoice?", "When is the annual bearing inspection due?"],
  questionReplies: ["We checked your trailer service record and sent the details.", "The shop will contact you about the next inspection slot."],
  jobNotes: ["Customer will bring the towing vehicle.", "Check coupler and lighting before pickup.", "Customer prefers text updates."],
};
